- package-lock.json
- package.json
- src/components/PersonalMenu/index.js
- src/components/Resources/index.js
- src/components/Search/index.js
[x] Set up axios to return resources
[x] Create skeleton for Search and PersonalMenu
[x] Install material-ui icons
> Set up axios 

- src/components/Nav/index.js
This PR is to solved issue #14.
Added a new nav item with user icon which will expand to show a menu list when it is clicked.
I have utilised material icon UI library for both the icon and the menu components.  
Implementation is shown in the screenshot below:
> Added user icon in nav with menu dropdown

- src/components/Resources/index.js
Fixes Issue #27 
Added base styling of material-ui TextAreaAutoSizeComponent in the Resources index.js file
> Updated base css styling of material-ui TextAreaAutoSize Component, #27

- src/components/Resources/ResourceCard.js
- src/components/Resources/index.js
This PR is to fix issue #26 🎉
- Fixed the bug on clicking the "toggle" button will opens up all the resource card
- Refactored to put the Card component into a separate file called `ResourceCard` in order to avoid bloating in the Resources index file.
- Fixed the minor bug on the wrong reference of the API endpoint
> Refactor resource card and fix the handler for expanding the card

- README.md
Saw your Hacktoberfest request for documentation help over on #12.  This isn't going to blow anyone's mind, but here's some information to help people get started with Material-UI.
> Ref #12 - Add Material-UI info to the README

- package-lock.json
- package.json
- src/App.js
- src/components/Resources/submitResource.js
For [Issue 16](https://github.com/codebuddies/react-concept/issues/16)
- Created a form for submitting resources.
- Included necessary event handlers
> Resources Submit Page

- src/App.js
- src/components/Resources/submitResource.js
Remove unused variables that are shown as warning in the console.
> Remove unused variables 

- package-lock.json
- package.json
I've added some new packages (`lint-staged`, `prettier`, `prettier-check`, `husky`) to help format code automatically whenever anyone commit changes. This is so that there is a consistency in terms of the code format. 
Feel free to reject this PR if this is not necessary.
> Format code when commit changes

- src/components/Nav/index.js
- src/components/PersonalMenu/index.js
Added some items to flesh out the personal menu UI. No interactivity yet.
> Personal Menu UI

- src/components/Resources/submitResource.js
fixes #41 
Formatting is done by prettier, not me
> Fix link to resources on submitResource page

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> Add PR and Issue Templates

- package-lock.json
Update Handlebars to fix vulnerability issue.
> Update Handlebar dependency

- .eslintrc.json
- .prettierrc.json
- jest.config.js
- package-lock.json
- package.json
- src/App.js
- src/App.test.js
- src/components/About/index.js
- src/components/About/index.stories.js
- src/components/Coworking/index.js
- src/components/Coworking/index.stories.js
- src/components/Home/index.js
- src/components/Home/index.stories.js
- src/components/Nav/index.js
- src/components/Nav/index.stories.js
- src/components/PersonalMenu/index.js
- src/components/PersonalMenu/index.stories.js
- src/components/Resources/ResourceCard.js
- src/components/Resources/ResourcePage.js
- src/components/Resources/index.js
- src/components/Resources/index.stories.js
- src/components/Resources/submitResource.js
- src/components/Search/index.js
- src/components/Search/index.stories.js
Set up ESLint and Prettier configurations and rules. 
Fix formatting issues and current linting issues.
Handles #78
> Setup ESLint and Prettier

- .storybook/preview.js
Storybook is not importing global css right now, which makes stuff like Fonts look wrong. I just imported the global `index.css` file into storybook.
> add global styles

- .eslintrc.json
- src/components/Resources/ResourceCard.js
- src/components/Resources/ResourcePage.js
Fixes #82
Add missing propTypes for components that don't have them.
> add propTypes to components

- .github/workflows/tests.yml
Adds Github actions for testing
Closes #83
> Add Github Actions for Testing

- .gitignore
Add my workspace files to .gitignore. It doesn't need to be checked in.
> Add workspace files to gitignore

- LICENSE
Can't believe I forgot to do this from the start, heh. We need to make sure we have a license before we apply to https://sentry.io/for/open-source/
> Create a license for this repo

- .env.example
- .gitignore
- README.md
Update development instructions in README to add .env file.
> Add SKIP_PREFLIGHT_CHECK to .env

- README.md
Added the Netlify and Gitduck logos to the README, per terms on opencollective.com/codebuddies
> Added a sponsors section to the README

- .github/stale.yml
Adds stale bot (https://github.com/marketplace/stale) to this repo so that stale issues are automatically closed.
N/A
[x] Installed https://github.com/marketplace/stale from the marketplace
[x] Added stale.yml file
N/A
Filed issue #43 as a next step to do after this PR is merged.
> Added stale.yml file

- README.md
README.md update :)
Before:
After: 
See: https://duckly.com/blog/gitduck-is-now-duckly/
N/A
> [Issue 177] Gitduck -> Duckly rebrand
